-- SETUP AUTH TABLES
-- Creates Roles, Permissions, and Profiles tables required by AuthContext.tsx

-- 1. Roles Table
CREATE TABLE IF NOT EXISTS public.roles (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    is_system boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Role Permissions Table
CREATE TABLE IF NOT EXISTS public.role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id uuid REFERENCES public.roles(id) ON DELETE CASCADE,
    route_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(role_id, route_key)
);

-- 3. Profiles Table (Linked to Auth Users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name text,
    email text,
    role_id uuid REFERENCES public.roles(id),
    status text DEFAULT 'Pendente',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    approved_by uuid,
    approved_at timestamp with time zone
);

-- Enable RLS
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Creating basic policies (can be refined later)
CREATE POLICY "Public read roles" ON public.roles FOR SELECT USING (true);
CREATE POLICY "Public read permissions" ON public.role_permissions FOR SELECT USING (true);
CREATE POLICY "Public read profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 4. Insert Default Roles
INSERT INTO public.roles (name, description, is_system)
VALUES 
('admin', 'Administrador do sistema - acesso total', true),
('usuario', 'Usuário do sistema - acesso intermediário', true)
ON CONFLICT (name) DO NOTHING;

-- 5. Insert Default Permissions
DO $$
DECLARE
    admin_id uuid;
    usuario_id uuid;
  
BEGIN
    SELECT id INTO admin_id FROM public.roles WHERE name = 'admin';
    SELECT id INTO usuario_id FROM public.roles WHERE name = 'usuario';


    -- Admin
    IF admin_id IS NOT NULL THEN
        INSERT INTO public.role_permissions (role_id, route_key) VALUES
        (admin_id, 'dashboard'), (admin_id, 'insights'), (admin_id, 'pipeline'), (admin_id, 'chat'), (admin_id, 'leads'), (admin_id, 'knowledge'), (admin_id, 'users')
        ON CONFLICT DO NOTHING;
    END IF;

    -- Usuario
    IF usuario_id IS NOT NULL THEN
        INSERT INTO public.role_permissions (role_id, route_key) VALUES
        (usuario_id, 'dashboard'), (usuario_id, 'insights'), (usuario_id, 'pipeline'), (usuario_id, 'chat'), (usuario_id, 'leads'), (usuario_id, 'knowledge')
        ON CONFLICT DO NOTHING;
    END IF;


END $$;
