-- Enable pgvector extension if not already enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- DROP tables first to ensure we replace the 'GENERATED ALWAYS' definitions
-- WARNING: This deletes data in these specific tables. Since you are importing fresh data, this is safe.
DROP TABLE IF EXISTS public.requests_products CASCADE;
DROP TABLE IF EXISTS public.requests CASCADE;
DROP TABLE IF EXISTS public.stock_products CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.attributes_schema CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.error CASCADE;
DROP TABLE IF EXISTS public.n8n_chat_histories CASCADE;
DROP TABLE IF EXISTS public.pagesUrl CASCADE;
DROP TABLE IF EXISTS public.stockUrl CASCADE;
DROP TABLE IF EXISTS public.rag_categories CASCADE;
DROP TABLE IF EXISTS public.rag_compatibility CASCADE;
DROP TABLE IF EXISTS public.rag_documents CASCADE;
DROP TABLE IF EXISTS public.rag_products CASCADE;


-- Re-create tables with 'GENERATED BY DEFAULT' (allows CSV import of IDs)

CREATE TABLE public.attributes_schema (
  att_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  product_name_core text NOT NULL,
  category text,
  compatibility text,
  attributes_key jsonb,
  attributes_alt jsonb,
  product_title text,
  CONSTRAINT attributes_schema_pkey PRIMARY KEY (att_id)
);

CREATE TABLE public.clients (
  client_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name_first text,
  name_last text,
  email text,
  whatsapp text NOT NULL,
  cpf_cnpj text,
  cep text,
  last_message timestamp with time zone DEFAULT now(),
  fup_done boolean DEFAULT false,
  company_name text,
  archived boolean DEFAULT false,
  CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

CREATE TABLE public.error (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  workflow_id bigint,
  workflow_name text,
  lastNodeExecuted text,
  error_message text,
  execution_id text,
  CONSTRAINT error_pkey PRIMARY KEY (id)
);

CREATE TABLE public.n8n_chat_histories (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  session_id character varying NOT NULL,
  message jsonb NOT NULL,
  CONSTRAINT n8n_chat_histories_pkey PRIMARY KEY (id)
);

CREATE TABLE public.pagesUrl (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  categoria text NOT NULL,
  nivel bigint,
  url text NOT NULL,
  page bigint,
  total_items bigint,
  done boolean,
  Categoria_pai text,
  url_pai text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  total_sub_items_mapped bigint,
  sub_URLs bigint,
  error boolean,
  error_obs text,
  scraped boolean,
  updated_at timestamp with time zone,
  supplier integer,
  CONSTRAINT pagesUrl_pkey PRIMARY KEY (id)
);

-- RAG Tables
CREATE TABLE public.rag_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  content text,
  metadata jsonb,
  embedding vector, 
  CONSTRAINT rag_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE public.rag_compatibility (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  content text,
  metadata jsonb,
  embedding vector,
  status text,
  CONSTRAINT rag_compatibility_pkey PRIMARY KEY (id)
);

CREATE TABLE public.rag_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  content text,
  metadata jsonb,
  embedding vector,
  CONSTRAINT rag_documents_pkey PRIMARY KEY (id)
);

CREATE TABLE public.rag_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  content text,
  metadata jsonb,
  embedding vector,
  status text,
  CONSTRAINT rag_products_pkey PRIMARY KEY (id)
);

CREATE TABLE public.requests (
  request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  client_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  status text,
  comments text,
  cep text,
  freight_cost numeric,
  freight_time bigint,
  closed_at timestamp with time zone,
  ordered_prods jsonb,
  prods_price numeric,
  total_price numeric,
  archived boolean DEFAULT false,
  CONSTRAINT requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT requests_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);

CREATE TABLE public.suppliers (
  supplier_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  cep text,
  apex_domain text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id)
);

CREATE TABLE public.stock_products (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_title text NOT NULL,
  url text,
  long_description text,
  short_description text,
  unit_price numeric NOT NULL,
  brand text,
  url_image text,
  register_date timestamp with time zone DEFAULT now(),
  car_models jsonb,
  details_height numeric,
  details_width numeric,
  details_length numeric,
  details_weight numeric,
  supplier_id bigint,
  product_category text,
  main_features jsonb,
  details_prod_source boolean,
  CONSTRAINT stock_products_pkey PRIMARY KEY (product_id),
  CONSTRAINT stock_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(supplier_id)
);

CREATE TABLE public.requests_products (
  prod_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  request_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  prod_title text NOT NULL,
  part_number text DEFAULT 'n/d'::text,
  car_brand text,
  car_model text,
  car_year bigint,
  car_version text,
  search_result boolean,
  search_prod_ids text[], -- Array of text
  result_saving bigint,
  prod_quantity bigint NOT NULL,
  attributes_key text,
  attributes_values jsonb,
  status text,
  prod_name_core text,
  search_freight jsonb,
  deal_status text,
  closed_at timestamp with time zone,
  selected_id bigint,
  selected_freight jsonb,
  draft_item text,
  CONSTRAINT requests_products_pkey PRIMARY KEY (prod_id),
  CONSTRAINT requested_parts_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(request_id)
);

CREATE TABLE public.stockUrl (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  title text NOT NULL,
  url text NOT NULL,
  price numeric NOT NULL,
  image_url text,
  scraped boolean,
  error boolean,
  error_obs text,
  updated_at timestamp with time zone,
  success boolean NOT NULL DEFAULT false,
  product_id bigint,
  supplier integer,
  CONSTRAINT stockUrl_pkey PRIMARY KEY (id)
);

-- Enable RLS (Recommended)
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access for authenticated users" ON public.requests
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow read access for authenticated users" ON public.clients
FOR SELECT USING (auth.role() = 'authenticated');
