-- Script specifically to fix the "identity column defined as GENERATED ALWAYS" error
-- Run this if you already have the tables created but can't import CSV data into the ID columns.

ALTER TABLE public.attributes_schema ALTER COLUMN att_id SET GENERATED BY DEFAULT;
ALTER TABLE public.clients ALTER COLUMN client_id SET GENERATED BY DEFAULT;
ALTER TABLE public.error ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.n8n_chat_histories ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.pagesUrl ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.rag_categories ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.rag_compatibility ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.rag_documents ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.rag_products ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.requests ALTER COLUMN request_id SET GENERATED BY DEFAULT;
ALTER TABLE public.suppliers ALTER COLUMN supplier_id SET GENERATED BY DEFAULT;
ALTER TABLE public.stock_products ALTER COLUMN product_id SET GENERATED BY DEFAULT;
ALTER TABLE public.requests_products ALTER COLUMN prod_id SET GENERATED BY DEFAULT;
ALTER TABLE public.stockUrl ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Ensure the array type for search_prod_ids is correct (fix for previous error)
ALTER TABLE public.requests_products ALTER COLUMN search_prod_ids TYPE text[];
