-- "NUCLEAR OPTION"
-- This script explicitly DROPS the tables that are giving errors and recreates them with "GENERATED BY DEFAULT".
-- Run this script in the SQL Editor. After running, try importing the CSV again.

-- 1. FIX PAGESURL
DROP TABLE IF EXISTS public."pagesUrl" CASCADE;
DROP TABLE IF EXISTS public.pagesurl CASCADE;

CREATE TABLE public.pagesUrl (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  categoria text,
  nivel bigint,
  url text,
  page bigint,
  total_items bigint,
  done boolean,
  "Categoria_pai" text, -- Quoted to preserve case if needed by CSV
  url_pai text,
  created_at timestamp with time zone DEFAULT now(),
  total_sub_items_mapped bigint,
  "sub_URLs" bigint,
  error boolean,
  error_obs text,
  scraped boolean,
  updated_at timestamp with time zone,
  supplier integer,
  CONSTRAINT pagesUrl_pkey PRIMARY KEY (id)
);

-- 2. FIX ATTRIBUTES_SCHEMA
DROP TABLE IF EXISTS public.attributes_schema CASCADE;

CREATE TABLE public.attributes_schema (
  att_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  product_name_core text,
  category text,
  compatibility text,
  attributes_key jsonb,
  attributes_alt jsonb,
  product_title text,
  CONSTRAINT attributes_schema_pkey PRIMARY KEY (att_id)
);

-- 3. FIX N8N_CHAT_HISTORIES (Just in case)
DROP TABLE IF EXISTS public.n8n_chat_histories CASCADE;

CREATE TABLE public.n8n_chat_histories (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  session_id character varying NOT NULL,
  message jsonb NOT NULL,
  CONSTRAINT n8n_chat_histories_pkey PRIMARY KEY (id)
);
