-- Migration Script to align with Future Schema
-- Preserves 'profiles', 'knowledge_files', 'roles', 'role_permissions'
-- Drops 'ai_settings'
-- Renames/Recreates 'pagesurl' -> 'pagesUrl', 'stockurl' -> 'stockUrl'

-- 1. DROP DEPRECATED TABLES
DROP TABLE IF EXISTS public.ai_settings CASCADE;

-- 2. UPDATE pagesUrl
DROP TABLE IF EXISTS public.pagesurl CASCADE;
DROP TABLE IF EXISTS public."pagesUrl" CASCADE;

CREATE TABLE public."pagesUrl" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  categoria text NOT NULL,
  nivel bigint,
  url text NOT NULL,
  page bigint,
  total_items bigint,
  done boolean,
  "Categoria_pai" text, -- Uppercase C from Future Schema
  url_pai text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  total_sub_items_mapped bigint,
  "sub_URLs" bigint, -- CamelCase from Future Schema
  error boolean,
  error_obs text,
  scraped boolean,
  updated_at timestamp with time zone,
  supplier integer,
  CONSTRAINT "pagesUrl_pkey" PRIMARY KEY (id)
);

-- 3. UPDATE stockUrl
DROP TABLE IF EXISTS public.stockurl CASCADE;
DROP TABLE IF EXISTS public."stockUrl" CASCADE;

CREATE TABLE public."stockUrl" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  title text NOT NULL,
  url text NOT NULL,
  price numeric NOT NULL,
  image_url text,
  scraped boolean,
  error boolean,
  error_obs text,
  updated_at timestamp with time zone,
  success boolean NOT NULL DEFAULT false,
  product_id bigint,
  supplier integer,
  CONSTRAINT "stockUrl_pkey" PRIMARY KEY (id)
);

-- 4. UPDATE error
DROP TABLE IF EXISTS public.error CASCADE;
CREATE TABLE public.error (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'::text),
  workflow_id bigint,
  workflow_name text,
  "lastNodeExecuted" text, -- CamelCase
  error_message text,
  execution_id text,
  CONSTRAINT error_pkey PRIMARY KEY (id)
);

-- 5. UPDATE clients (Preserved archived, company_name)
DROP TABLE IF EXISTS public.clients CASCADE;
CREATE TABLE public.clients (
  client_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name_first text,
  name_last text,
  email text,
  whatsapp text NOT NULL,
  cpf_cnpj text,
  cep text,
  last_message timestamp with time zone DEFAULT now(),
  fup_done boolean DEFAULT false,
  -- KEPT COLUMNS:
  company_name text,
  archived boolean DEFAULT false,
  CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

-- 6. UPDATE requests (Preserved archived)
DROP TABLE IF EXISTS public.requests CASCADE;
CREATE TABLE public.requests (
  request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  client_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  status text,
  comments text,
  cep text,
  freight_cost numeric,
  freight_time bigint,
  closed_at timestamp with time zone,
  ordered_prods jsonb,
  prods_price numeric,
  total_price numeric,
  -- KEPT COLUMN:
  archived boolean DEFAULT false,
  CONSTRAINT requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT requests_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);

-- 7. RE-ENABLE RLS & POLICIES
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users" ON public.requests FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow read access for authenticated users" ON public.clients FOR SELECT USING (auth.role() = 'authenticated');
