-- CLEANUP SCRIPT
-- Objective: Keep only the 5 core requested tables + System/Auth tables.
-- Core Tables to KEEP: clients, n8n_chat_histories, requests, requests_products, stock_products.

-- 1. Remove Dependencies preventing deletion
-- 'stock_products' references 'suppliers'. We need to drop this constraint first.
ALTER TABLE IF EXISTS public.stock_products DROP CONSTRAINT IF EXISTS stock_supplier_id_fkey;
-- 'pagesUrl' might be referenced? Usually not.

-- 2. Drop Unused Tables
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public."pagesUrl" CASCADE;
DROP TABLE IF EXISTS public.pagesurl CASCADE; -- Case variant
DROP TABLE IF EXISTS public."stockUrl" CASCADE;
DROP TABLE IF EXISTS public.stockurl CASCADE; -- Case variant
DROP TABLE IF EXISTS public.error CASCADE;
DROP TABLE IF EXISTS public.attributes_schema CASCADE;

-- Drop RAG tables if they are not part of the core request (User didn't list them)
-- Assuming we want to start fresh or user only cares about the listed 5.
DROP TABLE IF EXISTS public.rag_categories CASCADE;
DROP TABLE IF EXISTS public.rag_compatibility CASCADE;
DROP TABLE IF EXISTS public.rag_documents CASCADE;
DROP TABLE IF EXISTS public.rag_products CASCADE;

-- 3. Verify Core Tables Existence and basic fixups
-- Ensure stock_products doesn't rely on supplier_id anymore (it's kept as integer/bigint but no FK)
ALTER TABLE public.stock_products ALTER COLUMN supplier_id DROP NOT NULL;

-- 4. Ensure n8n_chat_histories is robust (Identity column)
ALTER TABLE public.n8n_chat_histories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Tables that should remain:
-- clients
-- n8n_chat_histories
-- requests
-- requests_products
-- stock_products
-- (plus profiles, roles, role_permissions, ai_settings)
